services:
  redis-db:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis-db:/data
volumes:
  redis-db:
    driver: local